version: '3'

services:
  kafka:
    image: wurstmeister/kafka:2.13-2.8.0
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_CREATE_TOPICS: "transactions:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9092:9092"

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  bank-portal:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - kafka
