apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebanking-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ebanking-portal
  template:
    metadata:
      labels:
        app: ebanking-portal
    spec:
      containers:
      - name: ebanking-portal
        image: eddie56/ebanking-portal:latest
        ports:
        - containerPort: 8080
        env:
        - name: KAFKA_BROKER_URL
          value: "kafka1:19092"

---

apiVersion: v1
kind: Service
metadata:
  name: ebanking-portal
  labels:
    app: ebanking-portal
spec:
  type: NodePort
  selector:
    app: ebanking-portal
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30100
