apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka1
spec:
  serviceName: "kafka"
  replicas: 1
  selector:
    matchLabels:
      app: kafka1
  template:
    metadata:
      labels:
        app: kafka1
    spec:
      containers:
      - name: kafka1
        image: confluentinc/cp-kafka:7.3.2
        ports:
          - containerPort: 19092
        env:
        - name: KAFKA_ADVERTISED_LISTENERS
          value: INTERNAL://kafka1:19092
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: INTERNAL:PLAINTEXT
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: INTERNAL
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zoo1:2181"
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
          value: "1"

---

apiVersion: v1
kind: Service
metadata:
  name: kafka1
  labels:
    app: kafka1
spec:
  selector:
      app: kafka1
  ports:
  - name: broker
    protocol: TCP
    port: 19092
    targetPort: 19092


